### ISSUE TITLE
Can not view code

### ISSUE THREAD

**Issue by Omnomios** [desplesda/Prockgen#1]
I've ran into a problem where the source code as an example for automating Blender does not exist and can't be viewed.

I have tested this on all major browsers and the bug affects all users. Further to this I have attempted to view the files on Windows 10 and Linux (Kernel 4.19) so it's not a platform issue.

**Priority:** P0 - Critical
**Version:** all versions
**Steps to reproduce:**
  1. Clone git repository locally
  2. Look in folder

**Comment by desplesda** [comment]
Apologies! Looks like I'd entirely forgotten to push the code. This is now done.
